# Change these first
owner: dankolbman
repo: avasaur-status

sites:
  - name: Avasaur Marketing
    url: https://avasaur.com
  - name: Avasaur App
    url: https://app.avasaur.com
    
status-website:
  baseUrl: /avasaur-status
  name: Avasaur Status Site
