# Change these first
owner: dankolbman
repo: avasaur-status

sites:
  - name: Avasaur Marketing
    url: https://avasaur.com
  - name: Avasaur App
    url: https://app.avasaur.com
    
status-website:
  baseUrl: /avasaur-status
  name: Avasaur Status Site
  logoUrl: https://raw.githubusercontent.com/dankolbman/avasaur/master/assets/logo_256_mark.png?token=AATBLFRZC3F6QOEALJSZN5LBHN5C4
  cname: status.avasaur.com
  publish: true